shoppu/config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

  get 'signup' => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'order_requests/accept' => 'order_requests#accept'
  get 'order_requests/show_all' => 'order_requests#show_all'
  get 'order_requests/show_open' => 'order_requests#show_open'
  get 'order_requests/show_all_accepted' => 'order_requests#show_all_accepted'
  get 'order_requests/show_all_completed' => 'order_requests#show_all_completed'
  get 'order_requests/show_one_accepted' => 'order_requests#show_one_accepted'
  get 'order_requests/hide' => 'order_requests#hide'

  resources :users

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :order_requests do
    resources :order_items do
      member do
        patch :complete
      end
    end
  end

  match ':controller(/:id(/:action))', :via => :get
end

shoppu/app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order_request

  has_attached_file :photo,
                    :styles => { :small => "150x150>" },
                    :storage => :s3,
                    :s3_region => ENV['S3_REGION'],
                    :bucket => ENV['S3_BUCKET_NAME'],
                    :endpoint => ENV['AWS_ENDPOINT'],
                    :s3_permissions => ENV['S3_PERMS']

  validates_attachment_size :photo, :less_than => 3.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']

  def completed?
    !completed_at.blank?
  end
end

shoppu/app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  # before_action :set_order_request
  before_action :logged_in_user #, only: [:create, :destroy]

  before_action except: [:complete] do
    set_order_request("owner")
  end

  before_action only: [:complete] do
    set_order_request("servicer")
  end

  before_action :set_order_item

  before_action :correct_user, except: [:create]

  def create
		@order_item = @order_request.order_items.create(order_item_params)
    flash[:success] = "Order item was added."
		redirect_to @order_request
	end

  def destroy
    if @order_item.present?
  		if @order_item.destroy
  			flash[:success] = "Order item was deleted."
  		else
  			flash[:error] = "Order item could not be deleted. [0x0204]"
  		end
    end
		redirect_to @order_request
	end

  def complete
		if @order_item.update_attribute(:completed_at, Time.now)
      # Check if all order_items are complete
      count_complete = 0

      @order_request.order_items.each do |order_item|
        if !order_item.completed_at.blank?
          count_complete += 1
        end
      end

      if count_complete == @order_request.order_items.size
        @order_request.update_attributes(:status => "completed")
		    redirect_to order_requests_show_all_completed_path, notice: "Order is complete! Thank you :)"
      else
        redirect_to order_requests_show_one_accepted_path(:id => @order_request.id), notice: "Order item completed"
      end
    else
      flash[:error] = "Failed to complete item - Please try again [0x0203]"
    end

	end

  private

  def set_order_request(user_type)
    if (user_type == "owner")
      @order_request = current_user.owned_orders.find_by_id(params[:order_request_id])
    elsif (user_type == "servicer")
      @order_request = current_user.serviced_orders.find_by_id(params[:order_request_id])
    else # force method to fail
      @order_request = nil
    end

    if @order_request.nil?
      flash[:error] = "A processing error has occurred - Sorry for the inconvenience [0x0200]"
      redirect_to root_url
    end
  end

  def set_order_item
    @order_item = @order_request.order_items.find_by_id(params[:id])
  end

  def correct_user
    if (@order_request.blank? || @order_item.blank?)
      flash[:error] = "A processing error has occurred - Sorry for the inconvenience [0x0201]"
      redirect_to root_url
    end
  end

  def order_item_params
    params[:order_item].permit(:content, :photo)
  end
end

shoppu/app/helpers/order_items_helper.rb
module OrderItemsHelper
end

shoppu/app/views/order_items/_form.html.erb
<%= form_for [@order_request, @order_request.order_items.build], html: { multipart: true } do |f| %>

	<%= f.label "Add new item" %>
	<%= f.text_field :content, :required => true, placeholder: "Add New Item Here", class: "form-control" %>

	<br>

	<%= f.label "Add photo for item (optional, max size 3MB)" %>
	<%= f.file_field :photo, class: "form-control" %>
	<br>

	<%= f.submit class: "btn btn-success btn-block"%>


<% end %>

shoppu/app/views/order_items/_order_item.html.erb
<!-- Use the bottom border of each render to seperate items -->
<div style = "border-bottom: 1px dotted #333; margin:5px;">
	<% if order_item.completed? %>
		<div class="order_item">
			<p style="opacity: 0.4; float:left;"><strike><%= order_item.content %></strike></p>
		</div>
		<% if @order_request.servicer_id == current_user.id %>
		<!-- Maybe we can add an "uncomplete" button here? -->
			<div class="complete" style="text-align:right;">
				<!-- <#%= link_to complete_order_request_order_item_path(@order_request, order_item.id), method: :patch do %> -->
					<button type="button" class="btn btn-success" style="visibility:hidden;"><i class="fa fa-check"></i>
					</button>
				<!-- <#% end %> -->
			</div>
		<% else %>
			<div class="trash" style="text-align:right;">
				<!-- <#%= link_to order_request_order_item_path(@order_request, order_item.id), method: :delete, data: { confirm: "Are you sure?" } do %> -->
					<button type="button" class="btn btn-danger btn-circle" style="visibility:hidden;"><i class="fa fa-trash"></i>
					</button>
				<!-- <#% end %> -->
			</div>
		<% end %>
	<% else %> <!-- else if order_item is not completed -->
		<div class="order_item">
			<p style="float:left;"><%= order_item.content %></p>
		</div>
		<% if @order_request.servicer_id == current_user.id %>
			<div class="complete" style="text-align:right;">
				<%= link_to complete_order_request_order_item_path(@order_request, order_item.id), method: :patch do %>
					<button type="button" class="btn btn-success"><i class="fa fa-check"></i>
					</button>
				<% end %>
			</div>
		<% else %>
			<div class="trash" style="text-align:right;">
				<%= link_to order_request_order_item_path(@order_request, order_item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
					<button type="button" class="btn btn-danger btn-circle"><i class="fa fa-trash"></i>
					</button>
				<% end %>
			</div>
		<% end %>
	<% end %>
	<% if order_item.photo.file? %>
		<div>
			<%= link_to image_tag(order_item.photo.url(:small), class: "small_image"), order_item.photo.url(:original) %>
		</div>
		<br>
	<% end %>
</div>