shoppu/config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

  get 'signup' => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'order_requests/accept' => 'order_requests#accept'
  get 'order_requests/show_all' => 'order_requests#show_all'
  get 'order_requests/show_open' => 'order_requests#show_open'
  get 'order_requests/show_all_accepted' => 'order_requests#show_all_accepted'
  get 'order_requests/show_all_completed' => 'order_requests#show_all_completed'
  get 'order_requests/show_one_accepted' => 'order_requests#show_one_accepted'
  get 'order_requests/hide' => 'order_requests#hide'

  resources :users

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :order_requests do
    resources :order_items do
      member do
        patch :complete
      end
    end
  end

  match ':controller(/:id(/:action))', :via => :get
end

shoppu/app/models/order_request.rb
class OrderRequest < ActiveRecord::Base
  has_many :order_items, dependent: :destroy
  accepts_nested_attributes_for :order_items
  validates :owner_id, presence: true

  validates :bounty, presence: true,
                     numericality: { :greater_than_or_equal_to => 0 }

  belongs_to :owner, :class_name => "User"
  default_scope -> { order(created_at: :desc) }
  belongs_to :servicer, :class_name => "User"

  validates :address, presence: true
  geocoded_by :address
  after_validation :geocode

end

shoppu/app/controllers/order_requests_controller.rb
class OrderRequestsController < ApplicationController
  before_action :logged_in_user #, only: [:create, :destroy]

  before_action only: [:correct_user, :show, :edit, :update, :destroy] do
     set_order_request("from_owner")
  end

  before_action only: [:accept] do
    set_order_request("from_all")
  end

  before_action only: [:show_one_accepted] do
    set_order_request("from_servicer")
  end

  before_action :correct_admin, only: [:hide, :show_all]

  # For users; Set all un-accepted orders by users
  def show_open
    # Selects open order_requests which have a positive number of order_items
    #  AND which belong to other users
    @order_requests = OrderRequest.select { |order_request| \
                      order_request.status == "open" && \
                      order_request.order_items.all.size > 0 && \
                      order_request.owner_id != current_user.id }
  end

  # For admins; Set all order requests made by all users
  def show_all
    @order_requests = OrderRequest.select {|order_request| order_request.status != "hidden"}
  end

  # For users who are servicers
  def show_all_accepted
    set_all("accepted")
  end

  # For user who is a servicer
  def show_one_accepted
  end

  # For user who is a servicer
  def show_all_completed
    set_all("completed")
  end

  # For user who is a servicer
  def accept
    if @order_request.update_attributes(:servicer_id => current_user.id, :status => "accepted")
      flash[:success] = 'Order request was successfully accepted.'
      set_all("accepted")
      render('show_all_accepted')
    else
      flash[:error] = "Failed to accept order - Please try again [0x0103]"
      redirect_to @user
    end
  end

  # For user who is a owner
  def index
    @order_requests = OrderRequest.all
  end

  # For user who is a owner
  def show
  end

  # For users
  def new
    @order_request = current_user.owned_orders.build
  end

  # For users
  def edit
  end

  # For users
  def create
    @order_request = current_user.owned_orders.build(order_request_params)

    respond_to do |format|
      if @order_request.save
        format.html { redirect_to @order_request, notice: 'Order request was successfully created.' }
        format.json { render :show, status: :created, location: @order_request }
      else
        format.html { render :new }
        format.json { render json: @order_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # For user who is a owner
  def update
    respond_to do |format|
      if !@order_request.update_attributes(order_request_params)
        format.html { render :edit }
        format.json { render json: @order_request.errors, status: :unprocessable_entity }
      end
      flash[:success] = "Order has been updated"
      format.html { redirect_to @order_request }
    end
  end

  # For admin
  def hide
    @order_request = OrderRequest.find_by_id(params[:id])
    @order_request.update_attributes(:status => "hidden")

    redirect_to order_requests_show_all_path
  end

  # For user who is a owner
  def destroy
    @order_request.destroy
    respond_to do |format|
      format.html { redirect_to order_requests_url, notice: 'Order request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_order_request(from_type)
      if from_type == "from_owner"
        @order_request = current_user.owned_orders.find_by_id(params[:id])
      elsif from_type == "from_servicer"
        @order_request = current_user.serviced_orders.find_by_id(params[:id])
      elsif from_type == "from_all"
        @order_request = OrderRequest.find_by_id(params[:id])
      else # force method to fail
        @order_request = nil
      end

      if @order_request.blank?
        flash[:error] = "A processing error has occurred - Sorry for the inconvenience [0x0100]"
        redirect_to root_url
        return
      end
    end

    # Selects order requests of a certain status which are serviced by current_user
    def set_all(status_type)
      @order_requests = OrderRequest.select { |order_request| \
                        order_request.status == status_type && \
                        order_request.servicer_id == current_user.id}
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_request_params
      params.require(:order_request).permit(:title, :bounty, :deliver_by, :accepted_at, :service_rating, :status, :description, :address, :longitude, :latitude)
    end

    def correct_admin
      if (!current_user.is_moderator?)
        flash[:error] = "A processing error has occurred - Sorry for the inconvenience [0x0102]"
        redirect_to root_url
      end
    end
end

shoppu/app/helpers/order_requests_helper.rb
module OrderRequestsHelper
end

shoppu/app/views/order_requests/_form.html.erb
<%= form_for(@order_request) do |f| %>
	<% if @order_request.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@order_request.errors.count, "error") %> prohibited this order_request from being saved:</h2>
			<ul>
				<% @order_request.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<%= f.label :title %>
	<div>
		<%= f.text_field :title, :required => true, style: 'width:100%',class: 'field' %>
	</div>
	<!-- <div class="field">
			<%= f.label :title %><br>
			<%= f.text_field :title %>
	</div> -->
	<%= f.label :bounty %>
	<div>
		<%= f.text_field :bounty, :required => true, class: 'field' %>
	</div>
	<!-- <div class="field">
			<%= f.label :bounty %><br>
			<%= f.text_field :bounty %>
	</div> -->
	<%= f.label :deliver_by %>
	<div>
		<%= f.datetime_select :deliver_by, class: 'field' %>
	</div>
	<!-- <div class="field">
			<%= f.label :deliver_by %><br>
			<%= f.datetime_select :deliver_by %>
	</div> -->

	<%= f.label :address %>
	<p class ="text-muted" style="text-align:left;"><small>Example: 1234 Abc Street, City, State/Province, Country</small></p>
	<div>
		<%= f.text_field :address, class: 'field', :required => true, value: @order_request.owner.address %>
	</div>

	<%= f.label :description %>
	<div>
		<%= f.text_field :description, class: 'field' %>
	</div>
	<br>
	<!-- <div class="field">
			<%= f.label :description %><br>
			<%= f.text_area :description %>
	</div> -->
	<div class="actions">
		<%= f.submit  %>
	</div>
<% end %>

shoppu/app/views/order_requests/edit.html.erb
<div class ="input_section">

<h1>Edit Order</h1>

<div class="forms">
	<%= render 'form' %>
</div>

<div class="links">
	<%= link_to 'Cancel', order_requests_path %>
</div>

</div>

shoppu/app/views/order_requests/index.html.erb
<% provide(:title, 'Your Orders') %>
<!--  The styling of the page can be found on the application.scss-->
<!--Changed div from input_section to container to give wider view -->
<div class="container">
	<div class="panel-default">
		<h1>My Orders</h1>
		<table class="table table-striped table-bordered table-hover">
			<!-- Adding the header of the table here -->
			<thead>
				<tr>
					<th style="width:30%">ORDER <small class="text-muted">Click on the order to view the details</small></th>
					<th style="width:55%">Description</th>
					<th style="width:15%">Status</th> <!-- add a color-coded status column -A */ -->
				</tr>
			</thead>
			<tbody>
				<% current_user.owned_orders.each do |order_request| %>
				<!--
				<div class="index_row clearfix">
						<h2 class="order_request_title"><%#= link_to order_request.title, order_request %></h2>
						<p class="order_request_sub_title"><#%= order_request.description %></p>
				</div>
				-->
				<tr>
					<td> <%= link_to order_request.title, order_request %></td>
					<td>
						<% if order_request.description.blank? %>
							<i>No description given</i>
						<% else %>
							<%= order_request.description %>
						<% end %>
					</td>
					<!--the following shows the colorcoded status -A*/-->
					<% if order_request.status=="open" %>
						<td style="background-color:#458B00">
							<i style="color:#FFFFFF">OPEN</i>
						</td>
					<% elsif order_request.status=="accepted" %>
						<td style="background-color:#FBDB0C">
							<i style="color:#FFFFFF">ACCEPTED</i>
						</td>
					<% elsif order_request.status=="completed" %>
						<td style="background-color:#8B8989">
							<i style="color:#FFFFFF">COMPLETED</i>
						</td>
					<% else %>
						<td style="background-color:#E3170D">
							<i style="color:#FFFFFF">HIDDEN</i>
						</td>
					<% end %>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
	<br>
	<div class="links">
		<%= link_to "New Order", new_order_request_path %> |
		<%= link_to "Back to profile", user_path(current_user.id) %>
	</div>
</div>

shoppu/app/views/order_requests/new.html.erb
<br>
<%= provide(:title, 'New Order') %>
<br>
<div class= "input_section">
	<h1 class="order_request_title" style="margin-top:30px; margin-bottom:30px">New Order</h1>
	<div class="forms">
		<%= render 'form' %>
	</div>
	<div class="links">
		<%= link_to 'Back to orders', order_requests_path %> | <%= link_to 'Back to profile', user_path(current_user) %>
	</div>
</div>

shoppu/app/views/order_requests/show.html.erb
<% provide(:title, @order_request.title) %>
<div class= "container">
	<p id="notice"><%= notice %></p>

	<div class="panel-default">
		<h1>My Order:</h1>
		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12">
				<div class= "panel panel-info">
					<div class= "panel-heading">
						<h2 class="order_request_title"><%= @order_request.title %></h2>
					</div>
					<div class ="panel-body" id="order_item_panel_head">
						<p class="order_request_sub_title"><strong>Description: </strong></p>
						<p>
							<% if @order_request.description.blank? %>
								<i>No description given</i>
							<% else %>
								<%= @order_request.description %>
							<% end %>
						</p>

						<p>
							<strong>Bounty: </strong>
							<%= number_to_currency(@order_request.bounty) %>
						</p>

						<p>
							<strong>Deliver By: </strong>
							<%= @order_request.deliver_by.to_s(:short) %>
						</p>

						<p><strong>Delivery Address:</strong></p>
						<p><%= @order_request.address %></p>
						<p><strong>Shopping List:</strong></p>
						<!--  Use Table to organize the item and the buttons, Styling of the table will be in custom.css-->
						<% if (@order_request.order_items.size > 0) %>
						<div style="border: solid 1px #555; padding: 5px; ">
							<%= render @order_request.order_items %>
						</div>
						<% else %>
						<i>No items currently in order</i>
						<% end %>
					</div>
					<div class="panel-footer" style="background-color:white;">
						<div id="form">
							<%= render "order_items/form" %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- </div> -->
	<div class="links">
		<%= link_to 'Edit', edit_order_request_path(@order_request) %> |
		<%= link_to 'Delete', order_request_path(@order_request), method: :delete, data: { confirm: "Are you sure?" }
		%> |
		<%= link_to 'Back', order_requests_path %>
	</div>
	<br>
	<div class="row">
		<div class="col-lg-12 col-md-12 col-sm-12">
			<div id="directions"></div>
		</div>
	</div>
</div>
<!--
<p>The longitude of this order is <%= @order_request.owner.longitude %></p>
<p>The latitude of this order is <%= @order_request.owner.latitude %></p>
-->
<!--  Styling of map can be found in static_page.css id= "directions"-->

<script type="text/javascript">
	handler = Gmaps.build('Google');
	handler.buildMap({ provider: {}, internal: {id: 'directions'}}, function(){
		markers = handler.addMarkers([
				{
					"lat": <%= @order_request.latitude %>,
					"lng": <%= @order_request.longitude %>,

					"infowindow": "<%= @order_request.owner.address %>"
				}
		]);
		handler.bounds.extendWith(markers);
		handler.fitMapToBounds();
		handler.getMap().setZoom(15);
	});
</script>


<!-- AIzaSyCLhOKE-GbE_RxFpCb16gXkaMreWzes7ks API key for browser -->

shoppu/app/views/order_requests/show_all.html.erb
<% provide(:title, 'All Public Orders') %>
<div class="container">
	<div class="panel-default">
		<h1>All Public Orders</h1>
		<% if @order_requests.blank? %>
			<h3>No orders have been created yet, surprisingly :O</h3>
		<% else %>
			<% @order_requests.each_with_index do |order_request, i| %>
				<!-- map javascript here-->
				<!--******************* -->
				<div class="panel panel-info" style="margin-bottom: 15px;">
					<div class="panel-heading">
						<p>
							<strong><%= i+1 %>.&nbsp;<%= order_request.title %> by
								<%= order_request.owner.username %>
								(<%= number_to_currency(order_request.bounty) %>)</strong>
						</p>
						<p style="font-family: monospace;">
							Created: <%= order_request.created_at %>
							</br>
							Updated: <%= order_request.updated_at %>
							</br>
							Status: <%= order_request.status %>
						</p>
					</div>
					<div class="panel-body">
						<p class="order_request_sub_title"><strong>Description: </strong></p>
						<p>
							<% if order_request.description.blank? %>
								<i>No description given</i>
							<% else %>
								<%= order_request.description %>
							<% end %>
						</p>
						<div style="border: solid 1px #555; padding: 5px; ">
							<p class="order_request_sub_title"><strong>List of Items: </strong></p>
							<% if order_request.order_items.empty? %>
								<i>No order items exist</i>
							<% else%>
								<ol class="order_item">
									<% order_request.order_items.each do |order_item| %>
										<li><%= order_item.content %></li>
										<br>
										<div>
										<% if order_item.photo.file? %>
												<%= link_to image_tag(order_item.photo.url(:small), class: "small_image"), order_item.photo.url(:original) %>
										<% else %>
											<i>No image provided</i>
										<% end %>
										</div>
										<br>
									<% end %>
								</ol>
							<% end %>
						</div>
					</div>
					<div class="panel-footer">
						<div>
							<%= link_to order_requests_hide_path(:id => order_request.id) do%>
							       <button type="button" class="btn btn-danger btn-lg btn-block"style="text-decoration:none;">Hide Order</button>
							<% end %>
						</div>
					</div>
				</div>
			<% end %>
		<% end %>
	</div>
</div>
<!--  The styling of the page can be found on the application.scss-->
<!--Changed div from input_section to container to give wider view -->

shoppu/app/views/order_requests/show_all_accepted.html.erb
<% provide(:title, 'Accepted Orders') %>
<!--  The styling of the page can be found on the application.scss-->
<!--Changed div from input_section to container to give wider view -->
<div class="container">
	<div class="panel-default">
		<h1>Orders Accepted By You:</h1>
		<% if @order_requests.blank? %>
			<h3>It's empty right now, but it doesn't have to be!</h3>
		<% else %>
			<table class="table table-striped table-bordered table-hover">
				<!-- Adding the header of the table here -->
				<thead>
					<tr>
						<th style="width:40%">Order <small class="text-muted">Click on the order to view the details</small></th>
						<th style="width:60%">Order Description</th>
					</tr>
				</thead>
				<tbody>
					<% @order_requests.each_with_index do |order_request, i| %>
					<tr>
						<td>
							<%= i+1 %>.&nbsp;
							<%#= order_request.title %>
							<%= link_to order_request.title, {:controller => :order_requests, :action => :show_one_accepted, :id => order_request.id} %>
							by <%= order_request.owner.username %>
							(<%= number_to_currency(order_request.bounty) %>) <br/>
							<small class="text-muted"> Updated <%= time_ago_in_words(order_request.updated_at) %> ago </small>
						</td>
						<td>
							<% if order_request.description.blank? %>
							<i>No description given</i>
							<% else %>
							<%= order_request.description %>
							<% end %>
						</td>
					</tr>
					<%end%>
				</tbody>
			</table>
		<% end %>
		<div class="links">
			<%= link_to "View Open Orders", order_requests_show_open_path %> |
			<%= link_to 'View Completed Orders', order_requests_show_all_completed_path %> |
			<%= link_to 'Back to profile', user_path(current_user) %>
		</div>
	</div>
	<br>
</div>

shoppu/app/views/order_requests/show_all_completed.html.erb
<% provide(:title, 'Completed Orders') %>
<div class="container">
	<div class="panel-default">
		<h1>Orders Completed By You:</h1>
		<% if @order_requests.blank? %>
			<h3>It's empty right now, but it doesn't have to be!</h3>
		<% else %>
			<% @order_requests.each_with_index do |order_request, i| %>
				<!-- map javascript here-->
				<!--******************* -->
				<div class="panel panel-info" style="margin-bottom: 15px;">
					<div class="panel-heading">
						<p>
							<strong><%= order_request.title %> by
								<%= order_request.owner.username %>
								(<%= number_to_currency(order_request.bounty) %>)</strong>
						</p>
					</div>
					<div class="panel-body">
						<p class="order_request_sub_title"><strong>Description: </strong></p>
						<p>
							<% if order_request.description.blank? %>
								<i>No description given</i>
							<% else %>
								<%= order_request.description %>
							<% end %>
						</p>
            <p class="order_request_sub_title"><strong>Order Address: </strong></p>
            <p>
              <% if order_request.address.blank? %>
                <i>No address given</i>
              <% else %>
                <%= order_request.address %>
              <% end %>
            </p>
            <p class="order_request_sub_title"><strong>Deliver By: </strong></p>
            <p>
              <%= order_request.deliver_by.to_s(:short) %>
            </p>
						<div style="border: solid 1px #555; padding: 5px; ">
							<p class="order_request_sub_title"><strong>List of Items: </strong></p>
							<% if order_request.order_items.empty? %>
								<i>No order items exist</i>
							<% else%>
								<ol class="order_item">
									<% order_request.order_items.each do |order_item| %>
										<li><%= order_item.content %></li>
										<br>
										<div>
										<% if order_item.photo.file? %>
												<%= link_to image_tag(order_item.photo.url(:small), class: "small_image"), order_item.photo.url(:original) %>
										<% else %>
											<i>No image provided</i>
										<% end %>
										</div>
										<br>
									<% end %>
								</ol>
							<% end %>
						</div>
					</div>
				</div>
			<% end %>
		<% end %>
    <br>
	  <div class="links">
	    <%= link_to "View Open Orders", order_requests_show_open_path %> |
	    <%= link_to 'Back', order_requests_show_all_accepted_path %>
	  </div>
	</div>
</div>
<!--  The styling of the page can be found on the application.scss-->
<!--Changed div from input_section to container to give wider view -->

shoppu/app/views/order_requests/show_one_accepted.html.erb
<% provide(:title, @order_request.title) %>
<!-- Styling in static_page.css -->
<div class= "container">
	<div class="panel-default">
		<h1>Current Accepted Order:</h1>
		<p id="notice"><%= notice %></p>
		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12">
				<div class= "panel panel-info">
					<div class= "panel-heading">
						<h2 class="order_request_title"><%= @order_request.title %></h2>
					</div>
					<div class ="panel-body" id="order_item_panel_head">
						<p class="order_request_sub_title"><strong>Description: </strong></p>
						<% if @order_request.description.blank? %>
							<i>No description given</i>
						<% else %>
							<%= @order_request.description %>
						<% end %>

						<p><strong>Address for Delivery: </strong></p>
						<p><%= @order_request.address %></p>

						<p><strong>Shopping List:</strong></p>
						<!--  Use Table to organize the item and the buttons, Styling of the table will be in custom.css-->
						<div style="border: solid 1px #555; padding: 5px; ">
							<%= render @order_request.order_items %>
						</div>
						<div class="links">
							<%= link_to 'Back', order_requests_show_all_accepted_path %>
						</div>
					</div>
				</div>
				<div id="directions"></div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
	var directionsDisplay = new google.maps.DirectionsRenderer();
	var directionsService = new google.maps.DirectionsService();

	function calcRoute(position) {
	  var origin      = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
	  var destination = new google.maps.LatLng(<%= @order_request.latitude %>, <%= @order_request.longitude %>);
	  var request = {
	      origin:      origin,
	      destination: destination,
	      travelMode:  google.maps.TravelMode.DRIVING
	  };
	  directionsService.route(request, function(response, status) {
	    if (status == google.maps.DirectionsStatus.OK) {
	      directionsDisplay.setDirections(response);
	    }
	  });
	}

	//getting current location for direction
	if(navigator.geolocation){

		navigator.geolocation.getCurrentPosition(calcRoute);

	}

	var handler = Gmaps.build('Google');
	handler.buildMap({ internal: {id: 'directions'}}, function(){
		directionsDisplay.setMap(handler.getMap());
	});
</script>


<!-- AIzaSyCLhOKE-GbE_RxFpCb16gXkaMreWzes7ks API key for browser -->

shoppu/app/views/order_requests/show_open.html.erb
<% provide(:title, 'Open Orders') %>
<div class="container">
	<div class="panel-default">
		<h1>Available Orders:</h1>

		<% if @order_requests.blank? %>
			<h3>No orders available - Please check back later</h3>
		<% else %>

		<div style='width: 100%;'>
			<div id="geolocation" style='height: 400px;'></div>
		</div>
		<p class ="text-muted"><small>Please click zoom out if there is no open order shown</small></p>

			<% @order_requests.each_with_index do |order_request, i| %>
				<!-- map javascript here-->
				<!--******************* -->
				<div class="panel panel-info" style="margin-bottom: 15px;" id ="<%=i%>" >
					<div class="panel-heading">
						<p><strong><%= i+1 %>.&nbsp;<%= order_request.title %> by <%= order_request.owner.username %>
						(<%= number_to_currency(order_request.bounty) %>)</strong> <small class="text-muted">Updated <%= time_ago_in_words(order_request.updated_at) %> ago </small></p>
					</div>
					<div class="panel-body">
						<p class="order_request_sub_title"><strong>Description: </strong></p>
						<p>
							<% if order_request.description.blank? %>
								<i>No description given</i>
							<% else %>
								<%= order_request.description %>
							<% end %>
						</p>
						<p><strong>Address for Delivery:</strong></p>
						<p><%= order_request.address%></p>

						<div style="border: solid 1px #555; padding: 5px; ">
							<p class="order_request_sub_title"><strong>List of Items: </strong></p>
							<ol class="order_item">
								<% if order_request.order_items.empty? %>
									<i>No order items exist</i>
								<% else%>
									<ol class="order_item">
										<% order_request.order_items.each do |order_item| %>
										<li><%= order_item.content %></li>
										<% end %>
									</ol>
								<% end %>
							</ol>
						</div>
					</div>
					<div class="panel-footer">
						<div>
							<%= link_to order_requests_accept_path(:id => order_request.id) do%>
							<button type="button" class="btn btn-success btn-lg btn-block"style="text-decoration:none;">Accept This Order</button>
							<% end %>
						</div>
					</div>
				</div>
			<% end %>
		<% end %>
		<div class="links">
			<%= link_to 'Back to profile', user_path(current_user) %>
		</div>
	</div>
</div>
<!--  The styling of the page can be found on the application.scss-->
<!--Changed div from input_section to container to give wider view -->


<script type="text/javascript">
var handler = Gmaps.build('Google');
handler.buildMap({ internal: {id: 'geolocation'} }, function(){
  if(navigator.geolocation)
    navigator.geolocation.getCurrentPosition(displayOnMap);


		var markers = handler.addMarkers([
			<% @order_requests.each_with_index do |order_request, i| %>
				{ lat: <%= order_request.latitude %>, lng: <%= order_request.longitude %>, infowindow: "<a href='#<%=i%>'><%= order_request.title%> by <%=order_request.owner.username%></a> <br/><%=order_request.address%>",},

			<% end %>


 	]);

		if(navigator.geolocation)
	    navigator.geolocation.getCurrentPosition(displayOnMap);


});

function displayOnMap(position){
  var marker = handler.addMarker({
    lat: position.coords.latitude,
    lng: position.coords.longitude,
		picture: {
			url: "http://mt.googleapis.com/maps/vt/icon/name=icons/spotlight/spotlight-waypoint-a.png&text=A&psize=16&font=fonts/Roboto-Regular.ttf&color=ff333333&ax=44&ay=48&scale=1",
			width:  36,
			height: 36
		},

		"infowindow": "You're Here"



  });
  handler.map.centerOn(marker);
	 handler.getMap().setZoom(15);
};
</script>