shoppu/config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

  get 'signup' => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'order_requests/accept' => 'order_requests#accept'
  get 'order_requests/show_all' => 'order_requests#show_all'
  get 'order_requests/show_open' => 'order_requests#show_open'
  get 'order_requests/show_all_accepted' => 'order_requests#show_all_accepted'
  get 'order_requests/show_all_completed' => 'order_requests#show_all_completed'
  get 'order_requests/show_one_accepted' => 'order_requests#show_one_accepted'
  get 'order_requests/hide' => 'order_requests#hide'

  resources :users

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :order_requests do
    resources :order_items do
      member do
        patch :complete
      end
    end
  end

  match ':controller(/:id(/:action))', :via => :get
end

shoppu/app/views/layouts/_body.html.erb
<body>
  <a id="menu-toggle" href="#" class="btn btn-dark btn-lg toggle mobileShow"> <i class = "fa fa-bars fa-3x"></i></a>
  <nav id="sidebar-wrapper" class ="mobileShow">
    <ul class="sidebar-nav">
      <a id="menu-close" href="#" class="btn btn-light btn-lg pull-right toggle"><i class="fa fa-times fa-3x"></i></a>
      <li class="sidebar-brand">
        <a href="../#top"  onclick = $("#menu-close").click(); >Start Bootstrap</a>
      </li>
      <li>
        <a href="../#top" onclick = $("#menu-close").click(); >Home</a>
      </li>
      <li>
        <a href="../#about" onclick = $("#menu-close").click(); >About</a>
      </li>
      <li>
        <a href="../#services" onclick = $("#menu-close").click(); >Services</a>
      </li>
      <% if logged_in? %>
      <li><%= link_to "Profile", current_user %></li>
      <li><%= link_to "Settings", edit_user_path(current_user) %></li>
      <li>
        <%= link_to "Log out", logout_path, method: "delete" %>
      </li>
      <% else %>
      <li><%= link_to "Log in", login_path %></li>
      <% end %>
      <li>
        <a href="#footer" onclick = $("#menu-close").click(); >Contact</a>
      </li>
    </ul>
  </nav>
  <!-- Navi header for the desktop browser -->
  <header style="margin-bottom:0px;" class="navbar navbar-inverse mobileHide">
    <div class="container">
      <%= link_to "SHOPPU", root_path, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <% if request.original_url != root_url %>
          <li><%= link_to "Home", root_url %></li>
          <% end %>
          <li><%= link_to "About", root_path(:anchor => "about") %></li>
          <li><%= link_to "How It Works", root_path(:anchor => "services") %></li>
          <li><%= link_to "Contact", root_path(:anchor => "footer") %></li>
          <% if logged_in? %>
            <% if current_user.is_moderator? %>
              <li><%= link_to "All Orders", order_requests_show_all_path %></li>
            <% end %>
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li><%= link_to "Log out", logout_path, method: "delete" %></li>
          <% else %>
            <li><%= link_to "Log in", login_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>
  <% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: "alert alert-info" %>
  <% end %>
  <%= yield %>

shoppu/app/views/layouts/_footer.html.erb
		<div id="footer">
			<h4 style="text-align:center;"><strong>SHOPPU</strong>
			</h4>
			<p>SFU<br>Burnaby, BC Canada</p>
			<p><i class="fa fa-phone fa-fw"></i> (123) 456-7890</p>
			<p>
				<i class="fa fa-envelope-o fa-fw"></i>  <a href="mailto:shoppumail@gmail.com">shoppumail@gmail.com</a>
			</p>
			<br>
			<hr class="small">
			<p class="text-muted">Copyright &copy; SHOPPU 2015</p>
		</div>

		<!-- Custom Theme JavaScript -->
		<script>
		// Closes the sidebar menu
		$("#menu-close").click(function(e) {
			e.preventDefault();
			$("#sidebar-wrapper").toggleClass("active");
		});

		// Opens the sidebar menu
		$("#menu-toggle").click(function(e) {
			e.preventDefault();
			$("#sidebar-wrapper").toggleClass("active");
		});

		// Scrolls to the selected menu item on the page
		$(function() {
			$('a[href*=#]:not([href=#])').click(function() {
				if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') || location.hostname == this.hostname) {
					var target = $(this.hash);
					target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
					if (target.length) {
						$('html,body').animate({
							scrollTop: target.offset().top
						}, 1000);
						return false;
					}
				}
			});
		});
		</script>
	</body>
</html>

shoppu/app/views/layouts/_head.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= yield(:title) %> | Shoppu</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css">

		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
		<script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
		<script src="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js"></script>
		
		<!-- java script from googlemap4rails -->
		<script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script>
		<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
		<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

		<!-- Custom Fonts -->
		<link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
		<%= csrf_meta_tags %>
	</head>

shoppu/app/views/layouts/application.html.erb
<%= render 'layouts/head' %>
<%= render 'layouts/body' %>
<%= render 'layouts/footer' %>